language: python

python:
- '3.8'

env: DJANGO_SETTINGS_MODULE="Projet_08.settings.travis"

services:
- postgresql

stages:
- test
- deploy

jobs:
  include:

  - stage: test
    before_script:
    - pip3 install -r requirements.txt
    script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test Auth.tests.test_base
    - python3 manage.py test Nutella.tests.test_base

  - stage: deploy
    addons:
      ssh_known_hosts: 37.187.116.21

    before_script: []
    env:
    - USER="manu"
    before_deploy: 
    - openssl aes-256-cbc -K $encrypted_50d31c429933_key -iv $encrypted_50d31c429933_iv
      -in id_rsa.enc -out id_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 id_rsa
    - ssh-add id_rsa
    - "pwd"
    deploy:
      provider: script
      skip_cleanup: true
      script: "ls"
      on branch: staging

