language: python
python:
  - '3.8'

before script:
  - pip3 install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="Projet_08.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python3 manage.py test Auth.tests.test_base
  - python3 manage.py test Nutella.tests.test_base

stages: 
  - deploy

jobs:
  include:
    - stage: deploy
      before_script: []
      env:
        - "USER=manu"
      script:
        - echo ssh $user@37.187.116.21

      branches:
        only:
          - staging
          - master

